
- name: Make sure pip install
  apt:
    name: python-pip

- name: Make sure python module install
  pip:
    name: docker-py


- name: Make sure work dir exists
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: yes
  with_items:
    - "{{ prometheus_data_dir }}"
    - "{{ prometheus_telegram_dir }}"

- name: Add prom configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0666
  with_items:
    - { src: "config.yml.j2", dest: "{{ prometheus_config_path }}" }
    - { src: "rules.yml.j2", dest: "{{ prometheus_rules_path }}" }
    - { src: "alertmanager_config.yml.j2", dest: "{{ prometheus_alertmanager_path }}" }


- name: Create prometheus containers
  docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: started
    restart: "{{ item.restart }}"
    volumes: "{{ item.volumes }}"
    ports: "{{ item.ports }}"
    command: "{{ item.command }}"
  with_items:
    - { name: "prometheus", image: "prom/prometheus", restart: yes, volumes: "{{ prometheus_data_dir }}:/prometheus-data", ports: "{{ prometheus_port }}:{{ prometheus_port }}", command: "--config.file=/prometheus-data/config.yml" }
    - { name: "pushgateway", image: "prom/pushgateway", restart: yes, volumes: None, ports: "{{ prometheus_pushgateway_port }}:{{ prometheus_pushgateway_port }}", command: "" }
    - { name: "alertmanager", image: "prom/alertmanager", restart: yes, volumes: "{{ prometheus_data_dir }}:/prometheus-data", ports: "{{ prometheus_alertmanager_port }}:{{ prometheus_alertmanager_port }}", command: "--config.file=/prometheus-data/alertmanager_config.yml" }


- name: Create tg bot
  docker_container:
    name: alertmanager_bot
    image: "metalmatze/alertmanager-bot:0.2"
    state: started
    restart: yes
    volumes: "{{ prometheus_telegram_dir }}:/data"
    ports: "{{ prometheus_telegram_port }}:{{ prometheus_telegram_port }}"
    env:
      ALERTMANAGER_URL: "http://{{ ansible_host }}:{{ prometheus_alertmanager_port }}"
      BOLT_PATH: "/data/bot.db"
      STORE: "bolt"
      TELEGRAM_ADMIN: "{{ prometheus_tg_id }}"
      LISTEN_ADDR: "0.0.0.0:8080"
      TELEGRAM_TOKEN: "{{ prometheus_tg_bot_token }}"